services:
   twilio-server:
      container_name: twilio-server
      build:
         context: .
         dockerfile: ${NODEJS_DOCKERFILE}
      ports:
         - "3001:3001"
      environment:
         - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
         - TWILIO_API_KEY=${TWILIO_API_KEY}
         - TWILIO_API_SECRET=${TWILIO_API_SECRET}
         - TWIML_APP_SID=${TWIML_APP_SID}
      volumes:
         - ./server:/app
         - /app/node_modules
      restart: unless-stopped
      networks:
         - test-network

   nginx:
      container_name: nginx
      image: nginx:latest
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./certbot/conf:/etc/letsencrypt # config for certbot certificates
         - ./certbot/www:/var/www/certbot # for certbot challenge
      deploy:
         replicas: ${NGINX_ENABLED:-1}
      restart: unless-stopped
      depends_on:
         - twilio-server
      networks:
         - test-network

   certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
      depends_on:
         - nginx
      deploy:
         replicas: ${CERTBOT_ENABLED:-1}
      networks:
         - test-network

networks:
   test-network:
      driver: bridge
